### PR TITLE
Storage manager can bootstrap data without an ajax call

### PR DESCRIPTION
**Pull request by juanca**
TODO
-

- [x] Needs specs!
- [x] Maybe refactor passing name down

@cantino @rogerneel 

@jrolfs

### CODE REVIEW

**Comment by juanca** [comment]
@ahuth @bgreg

**Comment by jrolfs** [comment]
This makes sense to me, I think it just needs specs.

**Comment by juanca** [comment]
Bump coffeescript version -- should match our other repos -- since it was requiring curly brackets in order to interpolate its a key.

**Comment by juanca** [comment]
I'm avoiding refactoring `name` argument which could be guessed from the `results` list in the response body. I'm assuming the `results` list could theoretically have different `key`s for a polymorphic fetch. But that's another bridge, another day.

**Comment by juanca** [comment]
@jrolfs I can has a peer review?

**Comment by jrolfs** [comment]
This looks good, I'm assuming for now we're not dealing with `include`s or did I miss something? If that's the case maybe it needs a little more coverage?

**Comment by juanca** [comment]
I'm going to look into how to test the includes stuff too. Will circle back then.

**Comment by juanca** [comment]
Seems like we don't care about includes in our cache key.

**Comment by juanca** [comment]
Thanks, mergin' to get this rolling.

**Pull request merged**
