### PR TITLE
Docs WIP

### PR DESCRIPTION
**Pull request by StephenGrider**
@jrolfs @cantino 

First pass at some docs just to get the ball rolling.  I made use of [codo](https://github.com/coffeedoc/codo), which generates documentation from inline comments.  Codo is a command-line tool installed by `npm install -g codo`.  Once installed, run `codo` from the root project folder to dump all the docs into `/doc`.  I picked Codo because it has some great support for coffeescript specific features like mixins.  It also has some first class support for defining `options` objects.

I pushed a generated copy of the docs to this repo's `gh-pages` branch, so you can see the docs I completed right now [here](http://mavenlink.github.io/brainstem-js/doc/).  Only `Brainstem.Model` and `Brainstem.Collection` have any progress right now, except for `fetch` on each one. 

Thoughts?

### CODE REVIEW

**Comment by diclophis** [comment]
@StephenGrider / @cantino any chance you could comment on what was remaining to be done on this branch... It would be much appreciated

**Comment by jrolfs** [comment]
We need to decide if this is the tool we want to use for documenting the API using CoffeeScript. Honestly I'd prefer to prioritize higher level documentation (ie: updating the readme) and moving away from CoffeeScript and then look at tooling to auto-generate API documentation.

**Comment by cantino** [comment]
The code comments, at least, would be nice if they're still accurate!  No strong opinion here, though.

**Comment by jrolfs** [comment]
Oh yeah, will definitely preserve those. Thanks Andrew ;)

**Comment by diclophis** [comment]
@rogerneel / @shirish-pampoorickal / @jhmoore is this the self-auto-doc branch for brainstem? or what is going on here?

**Comment by shirish-pampoorickal** [comment]
@diclophis No. The auto-doc generation code is on `docgen` branch (https://github.com/mavenlink/brainstem/pull/66)

**Comment by diclophis** [comment]
closing this PR, please re-open if desired

**Comment by jrolfs** [comment]
This is essentially defunct – I would shoot for JSDoc if we want to give this another go.

**Pull request closed without merging**
