### PR TITLE
Bump jQuery and npmignore

### PR DESCRIPTION
**Pull request by juanca**
@jrolfs Review appreciated.

### CODE REVIEW

**Comment by jrolfs** [comment]
Why are we bumping the patch number to 11?

**Comment by jrolfs** [comment]
Also these really should be separate PRs...

**Comment by juanca** [comment]
We were bumping the package number a little crazy-like last week (before we discovered `npm pack` command). So this is the next available patch number.

I agree on the separate PRs but let's just do it in the same branch for now? These changes are small and it was easiest to do it in the same branch to avoid having waaay too many moving parts.

**Comment by jrolfs** [comment]
In the future I think we should only be bumping the version number on master.

**Comment by juanca** [comment]
Oh. Whoops, I think I've been bumping the patch for each commit (to test against its usage elsewhere)

**Pull request merged**
