### PR TITLE
Fix coffeelint warnings and fail linting on warning

### PR DESCRIPTION
**Pull request by jrolfs**
- Fix all `warning` level CoffeeLint problems
- Enable `failOnWarning` CoffeeLint reporter to fail CI when code formatting is no good 💇

### CODE REVIEW

**Comment by jrolfs** [comment]
@naganowl @juanca let's get tooling up on this?

**Comment by naganowl** [comment]
Dig it! Gotta make CI happy though.

**Comment by naganowl** [comment]
Why did we get rid of this?

**Comment by juanca** [comment]
Probably too many warnings :p

**Comment by jrolfs** [comment]
I re-did it after merging the cache new model reference patch PR – #83

**Pull request closed without merging**
