### PR TITLE
Update Collection fetch method so chained callbacks receive collection instance.

### PR DESCRIPTION
**Pull request by jrolfs**
This passes the actual collection instance into the promise callback instead of an array of models. This makes `Collection#fetch` consistent with `Model#fetch`

### CODE REVIEW

**Comment by jrolfs** [comment]
@StephenGrider

**Comment by jrolfs** [comment]
@CacheFactory

**Comment by jrolfs** [comment]
@juanca can you take a quick peek?

**Comment by juanca** [comment]
w00t!

Looks good to me!

**Pull request merged**
