### PR TITLE
De gem ify

### PR DESCRIPTION
**Pull request by ahuth**
Remove all the old stuff around brainstem-js being a Ruby gem.

@naganowl can you take a look at this, please?

### CODE REVIEW

**Comment by naganowl** [comment]
Is there a mlJS branch to check that this is compatible?

**Comment by ahuth** [comment]
mavenlink-js doesn't have any gem dependencies. It doesn't actually even have a dependency on the brainstem-js npm package (it does have a peer dependency, though).

**Comment by ahuth** [comment]
I'll make a branch for big maven though, to make sure it's all green

**Comment by naganowl** [comment]
Just wanted to make sure that there was a complete lack of reference to the `vendor` assets elsewhere.

**Comment by ahuth** [comment]
Yeah, makes sense. Shouldn't be, but of course there's no telling. I'll get a big maven branch going. Thanks

**Comment by ahuth** [comment]
Everything looks good in https://github.com/mavenlink/mavenlink/pull/14584

**Comment by ahuth** [comment]
Thanks!

**Pull request merged**
