### PR TITLE
Fix the error message to include the collection name

### PR DESCRIPTION
**Pull request by JoeGaebel**
A bug from bigmaven left a console error of

```
Uncaught Error: Unable to find default_role with id 1231231 in our cached {details.collectionName} collection. We know about 123123, 123123, .... , fragment: pending
```

This PR cleans up that error message to actually output the collection name.

Compiled with `gulp build-gem`

### CODE REVIEW

**Comment by JoeGaebel** [comment]
It seems odd to me that this small coffee change created a large amount of other unrelated changes upon compilation. I believe this happened because it was not compiled in a while or some dependencies may have updated?

**Comment by bennapp** [comment]
I believe the gem is out of date.

**Comment by bennapp** [comment]
This LGTM. @naganowl What are you thoughts on `vendor/assets/javascripts/brainstem.js` and the gem being out of date?

**Comment by naganowl** [comment]
If we want to continue supporting the Gem aspect of this repo, we should bump https://github.com/mavenlink/brainstem-js/blob/master/lib/brainstem/js/version.rb as done in the last version bump https://github.com/mavenlink/brainstem-js/commit/a5ba813e90496201735b4bfa1077c60eee320ebf

**Comment by juanca** [comment]
Why does the diff contain so many unrelated things? :/

**Comment by naganowl** [comment]
We weren't updating the artifact for the Gem and we were storing artifacts still. I'd be for removing it but I don't even know who actually still use the Gem variant of this JS.

**Pull request merged**
